# === Base image ===
FROM python:3.12-slim

WORKDIR /app

# Copy requirements and install
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all python scripts and data folder
COPY ../*.py .
COPY ../data ./data

# Set environment variable for Python unbuffered output
ENV PYTHONUNBUFFERED=1

# Run the script
CMD ["python", "main.py"]
