# === Base image ===
FROM python:3.12-slim

WORKDIR /app

# Copy requirements and install
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy exporter script and data folder
COPY ../prometheus_exporter.py .
COPY ../data ./data

ENV PYTHONUNBUFFERED=1

# Expose port for Prometheus
EXPOSE 5000

CMD ["python", "prometheus_exporter.py"]
